'use client'
import ToolLayout from '@/components/tools/ToolLayout'
import { jsonToJson5, json5ToJson } from '@/lib/converters'

const example = '{"name":"JSONKits","version":"1.0.0","features":["fast","free"]}'

export default function ToolPageClient() {
  return (
    <>
      <ToolLayout
        title="JSON to JSON5 Converter"
        description="Convert standard JSON to JSON5 format with unquoted keys for cleaner configuration files."
        inputPlaceholder="Paste your JSON here..."
        outputPlaceholder="JSON5 output will appear here..."
        convertLabel="JSON to JSON5"
        onConvert={jsonToJson5}
        exampleInput={example}
        inputLanguage="json"
        outputLanguage="json"
        bidirectional
        onReverse={json5ToJson}
        toolSlug="json-to-json5"
      />
      <article className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-16 prose prose-slate dark:prose-invert">
        <h2>What Is Standard JSON?</h2>
        <p>Standard JSON (JavaScript Object Notation) is a lightweight, language-independent data interchange format defined by RFC 8259. It uses a strict syntax with double-quoted strings, no comments, and no trailing commas, making it reliable but verbose for human authors.</p>
        <h2>What Is JSON5?</h2>
        <p>JSON5 is a superset of JSON that aims to make writing configuration files and data by hand easier. It adds support for comments, unquoted keys, single-quoted strings, trailing commas, and more flexible numeric formats. JSON5 is ideal for projects where humans regularly author and maintain data files.</p>
        <p>JSON5 is perfect for:</p>
        <ul>
          <li><strong>Local Configs</strong>: Adding comments explaining configuration values.</li>
          <li><strong>Team Projects</strong>: Making configs more readable with unquoted keys.</li>
          <li><strong>Rapid Prototyping</strong>: Writing data quickly without strict syntax rules.</li>
          <li><strong>Tool Configurations</strong>: Many build tools accept JSON5 natively.</li>
        </ul>
        <h2>When to Convert JSON to JSON5</h2>
        <p>Converting standard JSON to JSON5 adds human-friendly features like comments and unquoted keys, making your configuration files more maintainable. This is especially useful when you manage configs by hand and want to document why certain values are set.</p>
        <h2>How to Convert JSON to JSON5 Online</h2>
        <ol>
          <li><strong>Paste your JSON</strong>: Copy your standard JSON data into the input box.</li>
          <li><strong>Click Convert</strong>: Press the button to transform your JSON into JSON5 format with unquoted keys where appropriate.</li>
          <li><strong>Review the Output</strong>: Check the cleaner JSON5 syntax and add comments as needed.</li>
          <li><strong>Copy & Deploy</strong>: Use the Copy button to save the JSON5 output for use in your project.</li>
        </ol>
        <h2>Frequently Asked Questions</h2>
        <h3>Is this JSON to JSON5 converter safe?</h3>
        <p>Absolutely. All processing happens 100% client-side in your browser. Your data is never uploaded to any server.</p>
        <h3>Can I add comments after conversion?</h3>
        <p>The converter removes quotes from keys where possible, but you can manually add comments to the output to document your configuration values.</p>
        <h3>Does JSON5 work everywhere?</h3>
        <p>No, JSON5 is not supported by all parsers. Use standard JSON for APIs and third-party integrations, and JSON5 for local configuration files that you maintain by hand.</p>
        <h2>Real-World Examples</h2>
        <p>A common workflow is to start with a standard JSON config file generated by a tool, then convert it to JSON5 to add documentation comments for other team members. This is particularly useful in monorepo setups where configuration files need to be self-documenting.</p>
        <h2>Related Tools</h2>
        <ul>
          <li><a href="/json5-to-json">JSON5 to JSON</a> — convert JSON5 back to standard JSON</li>
          <li><a href="/json-to-jsonc">JSON to JSONC</a> — add comments to JSON files</li>
          <li><a href="/json-formatter">JSON Formatter</a> — beautify and indent JSON data</li>
        </ul>
      </article>
    </>
  )
}
