import type { NavItem, Tool } from '@/types'

export const navItems: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Formatters', href: '/formatter' },
  { label: 'Validators', href: '/validator' },
  { label: 'Viewers', href: '/viewer' },
  { label: 'Converters', href: '/json-to-yaml' },
]

export const tools: Tool[] = [
  { id: 'formatter', name: 'JSON Formatter', description: 'Beautify and pretty-print your JSON with customizable indentation.', category: 'formatter', slug: '/formatter', icon: 'Braces' },
  { id: 'validator', name: 'JSON Validator', description: 'Check if your JSON is valid and get detailed error messages.', category: 'validator', slug: '/validator', icon: 'CheckCircle' },
  { id: 'viewer', name: 'JSON Viewer', description: 'View and explore JSON data in a readable tree structure.', category: 'viewer', slug: '/viewer', icon: 'Eye' },
  { id: 'minifier', name: 'JSON Minifier', description: 'Compress JSON by removing whitespace to reduce file size.', category: 'formatter', slug: '/minifier', icon: 'Compress' },
  { id: 'diff-checker', name: 'JSON Diff Checker', description: 'Compare two JSON objects and see the differences.', category: 'compare', slug: '/diff-checker', icon: 'Columns' },

  // Data Format Converters
  { id: 'json-to-yaml', name: 'JSON to YAML', description: 'Convert JSON data to YAML format for configuration files.', category: 'converter', slug: '/json-to-yaml', icon: 'ArrowRight' },
  { id: 'yaml-to-json', name: 'YAML to JSON', description: 'Convert YAML configuration files to JSON format.', category: 'converter', slug: '/yaml-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-csv', name: 'JSON to CSV', description: 'Transform JSON arrays into CSV spreadsheets.', category: 'converter', slug: '/json-to-csv', icon: 'Table' },
  { id: 'csv-to-json', name: 'CSV to JSON', description: 'Convert CSV data into structured JSON format.', category: 'converter', slug: '/csv-to-json', icon: 'FileText' },
  { id: 'json-to-xml', name: 'JSON to XML', description: 'Convert JSON data to XML format for SOAP APIs and legacy systems.', category: 'converter', slug: '/json-to-xml', icon: 'ArrowRight' },
  { id: 'xml-to-json', name: 'XML to JSON', description: 'Convert XML documents into structured JSON format.', category: 'converter', slug: '/xml-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-toml', name: 'JSON to TOML', description: 'Convert JSON to TOML format for Rust and Python project configs.', category: 'converter', slug: '/json-to-toml', icon: 'ArrowRight' },
  { id: 'toml-to-json', name: 'TOML to JSON', description: 'Convert TOML configuration files to JSON format.', category: 'converter', slug: '/toml-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-ini', name: 'JSON to INI', description: 'Convert JSON data to INI configuration format.', category: 'converter', slug: '/json-to-ini', icon: 'ArrowRight' },
  { id: 'ini-to-json', name: 'INI to JSON', description: 'Convert INI configuration files to JSON format.', category: 'converter', slug: '/ini-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-properties', name: 'JSON to Properties', description: 'Convert JSON to Java .properties format.', category: 'converter', slug: '/json-to-properties', icon: 'ArrowRight' },
  { id: 'properties-to-json', name: 'Properties to JSON', description: 'Convert Java .properties files to JSON format.', category: 'converter', slug: '/properties-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-tsv', name: 'JSON to TSV', description: 'Transform JSON arrays into tab-separated values.', category: 'converter', slug: '/json-to-tsv', icon: 'Table' },
  { id: 'tsv-to-json', name: 'TSV to JSON', description: 'Convert tab-separated values to structured JSON format.', category: 'converter', slug: '/tsv-to-json', icon: 'FileText' },
  { id: 'json-to-html-table', name: 'JSON to HTML Table', description: 'Convert JSON data to an HTML table.', category: 'converter', slug: '/json-to-html-table', icon: 'ArrowRight' },
  { id: 'html-table-to-json', name: 'HTML Table to JSON', description: 'Convert HTML tables to structured JSON format.', category: 'converter', slug: '/html-table-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-markdown-table', name: 'JSON to Markdown Table', description: 'Convert JSON data to a Markdown table.', category: 'converter', slug: '/json-to-markdown-table', icon: 'Table' },
  { id: 'markdown-table-to-json', name: 'Markdown Table to JSON', description: 'Convert Markdown tables to structured JSON format.', category: 'converter', slug: '/markdown-table-to-json', icon: 'FileText' },
  { id: 'json-to-plain-text', name: 'JSON to Plain Text', description: 'Flatten JSON objects into plain key: value text.', category: 'converter', slug: '/json-to-plain-text', icon: 'ArrowRight' },
  { id: 'plain-text-to-json', name: 'Plain Text to JSON', description: 'Convert key: value text back into JSON format.', category: 'converter', slug: '/plain-text-to-json', icon: 'ArrowLeft' },

  // Code Generators (JSON → Language)
  { id: 'json-to-typescript', name: 'JSON to TypeScript', description: 'Generate TypeScript interfaces from JSON samples.', category: 'converter', slug: '/json-to-typescript', icon: 'Code' },
  { id: 'json-to-python', name: 'JSON to Python', description: 'Generate Python dataclasses from JSON samples.', category: 'converter', slug: '/json-to-python', icon: 'Code' },
  { id: 'json-to-go', name: 'JSON to Go', description: 'Generate Go structs with JSON tags from JSON samples.', category: 'converter', slug: '/json-to-go', icon: 'Code' },
  { id: 'json-to-java', name: 'JSON to Java', description: 'Generate Java POJO classes from JSON samples.', category: 'converter', slug: '/json-to-java', icon: 'Code' },
  { id: 'json-to-csharp', name: 'JSON to C#', description: 'Generate C# classes with JSON attributes from JSON samples.', category: 'converter', slug: '/json-to-csharp', icon: 'Code' },
  { id: 'json-to-php-array', name: 'JSON to PHP Array', description: 'Convert JSON to PHP array syntax.', category: 'converter', slug: '/json-to-php-array', icon: 'Code' },
  { id: 'json-to-php-class', name: 'JSON to PHP Class', description: 'Generate PHP classes with getters/setters from JSON.', category: 'converter', slug: '/json-to-php-class', icon: 'Code' },
  { id: 'json-to-kotlin', name: 'JSON to Kotlin', description: 'Generate Kotlin data classes from JSON samples.', category: 'converter', slug: '/json-to-kotlin', icon: 'Code' },
  { id: 'json-to-swift', name: 'JSON to Swift', description: 'Generate Swift Codable structs from JSON samples.', category: 'converter', slug: '/json-to-swift', icon: 'Code' },
  { id: 'json-to-dart', name: 'JSON to Dart', description: 'Generate Dart model classes from JSON samples.', category: 'converter', slug: '/json-to-dart', icon: 'Code' },
  { id: 'json-to-rust', name: 'JSON to Rust', description: 'Generate Rust structs with Serde attributes from JSON.', category: 'converter', slug: '/json-to-rust', icon: 'Code' },
  { id: 'json-to-scala', name: 'JSON to Scala', description: 'Generate Scala case classes with Play JSON from JSON.', category: 'converter', slug: '/json-to-scala', icon: 'Code' },
  { id: 'json-to-ruby', name: 'JSON to Ruby', description: 'Convert JSON to Ruby hash syntax.', category: 'converter', slug: '/json-to-ruby', icon: 'Code' },
  { id: 'json-to-perl', name: 'JSON to Perl', description: 'Convert JSON to Perl data structure syntax.', category: 'converter', slug: '/json-to-perl', icon: 'Code' },
  { id: 'json-to-lua', name: 'JSON to Lua', description: 'Convert JSON to Lua table syntax.', category: 'converter', slug: '/json-to-lua', icon: 'Code' },
  { id: 'json-to-r', name: 'JSON to R', description: 'Convert JSON to R list syntax.', category: 'converter', slug: '/json-to-r', icon: 'Code' },
  { id: 'json-to-matlab', name: 'JSON to MATLAB', description: 'Convert JSON to MATLAB struct syntax.', category: 'converter', slug: '/json-to-matlab', icon: 'Code' },

  // Reverse Code Generators (Language → JSON)
  { id: 'typescript-interface-to-json', name: 'TypeScript Interface to JSON', description: 'Generate sample JSON data from TypeScript interface definitions.', category: 'generator', slug: '/typescript-interface-to-json', icon: 'Code' },
  { id: 'java-class-to-json', name: 'Java Class to JSON', description: 'Generate sample JSON data from Java class definitions.', category: 'generator', slug: '/java-class-to-json', icon: 'Code' },
  { id: 'csharp-class-to-json', name: 'C# Class to JSON', description: 'Generate sample JSON data from C# class definitions.', category: 'generator', slug: '/csharp-class-to-json', icon: 'Code' },
  { id: 'python-dict-to-json', name: 'Python Dict to JSON', description: 'Convert Python dictionary syntax to JSON format.', category: 'generator', slug: '/python-dict-to-json', icon: 'Code' },
  { id: 'go-struct-to-json', name: 'Go Struct to JSON', description: 'Generate sample JSON data from Go struct definitions.', category: 'generator', slug: '/go-struct-to-json', icon: 'Code' },
  { id: 'php-array-to-json', name: 'PHP Array to JSON', description: 'Convert PHP array syntax to JSON format.', category: 'generator', slug: '/php-array-to-json', icon: 'Code' },
  { id: 'kotlin-to-json', name: 'Kotlin to JSON', description: 'Generate sample JSON data from Kotlin data class definitions.', category: 'generator', slug: '/kotlin-to-json', icon: 'Code' },
  { id: 'swift-to-json', name: 'Swift to JSON', description: 'Generate sample JSON data from Swift struct definitions.', category: 'generator', slug: '/swift-to-json', icon: 'Code' },
  { id: 'dart-to-json', name: 'Dart to JSON', description: 'Generate sample JSON data from Dart model class definitions.', category: 'generator', slug: '/dart-to-json', icon: 'Code' },
  { id: 'rust-struct-to-json', name: 'Rust Struct to JSON', description: 'Generate sample JSON data from Rust struct definitions.', category: 'generator', slug: '/rust-struct-to-json', icon: 'Code' },

  // Encodings
  { id: 'json-to-base64', name: 'JSON to Base64', description: 'Encode JSON data to Base64 format.', category: 'converter', slug: '/json-to-base64', icon: 'ArrowRight' },
  { id: 'base64-to-json', name: 'Base64 to JSON', description: 'Decode Base64 data back to JSON format.', category: 'converter', slug: '/base64-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-url-encoded', name: 'JSON to URL Encoded', description: 'Convert JSON objects to URL-encoded format.', category: 'converter', slug: '/json-to-url-encoded', icon: 'ArrowRight' },
  { id: 'url-encoded-to-json', name: 'URL Encoded to JSON', description: 'Convert URL-encoded strings to JSON format.', category: 'converter', slug: '/url-encoded-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-hex', name: 'JSON to Hex', description: 'Convert JSON data to hexadecimal string representation.', category: 'converter', slug: '/json-to-hex', icon: 'ArrowRight' },
  { id: 'hex-to-json', name: 'Hex to JSON', description: 'Convert hexadecimal strings back to JSON format.', category: 'converter', slug: '/hex-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-unicode-escape', name: 'JSON to Unicode Escape', description: 'Convert JSON to Unicode escape sequences.', category: 'converter', slug: '/json-to-unicode-escape', icon: 'ArrowRight' },
  { id: 'unicode-escape-to-json', name: 'Unicode Escape to JSON', description: 'Convert Unicode escape sequences to readable JSON.', category: 'converter', slug: '/unicode-escape-to-json', icon: 'ArrowLeft' },

  // Web Formats
  { id: 'json-to-url-params', name: 'JSON to URL Parameters', description: 'Convert JSON objects to URL parameter format.', category: 'converter', slug: '/json-to-url-params', icon: 'ArrowRight' },
  { id: 'url-params-to-json', name: 'URL Parameters to JSON', description: 'Convert URL parameters back to JSON format.', category: 'converter', slug: '/url-params-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-query-string', name: 'JSON to Query String', description: 'Convert JSON objects to query string format.', category: 'converter', slug: '/json-to-query-string', icon: 'ArrowRight' },
  { id: 'query-string-to-json', name: 'Query String to JSON', description: 'Parse query strings into JSON format.', category: 'converter', slug: '/query-string-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-form-data', name: 'JSON to Form Data', description: 'Convert JSON objects to URL-encoded form data.', category: 'converter', slug: '/json-to-form-data', icon: 'ArrowRight' },
  { id: 'form-data-to-json', name: 'Form Data to JSON', description: 'Parse form data back into JSON format.', category: 'converter', slug: '/form-data-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-jsonp', name: 'JSON to JSONP', description: 'Convert JSON to JSONP with callback wrapper.', category: 'converter', slug: '/json-to-jsonp', icon: 'ArrowRight' },
  { id: 'jsonp-to-json', name: 'JSONP to JSON', description: 'Extract JSON from JSONP callback wrappers.', category: 'converter', slug: '/jsonp-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-js-object', name: 'JSON to JS Object', description: 'Convert JSON to JavaScript object literal syntax.', category: 'converter', slug: '/json-to-js-object', icon: 'Code' },
  { id: 'js-object-to-json', name: 'JS Object to JSON', description: 'Convert JavaScript object literals to JSON format.', category: 'converter', slug: '/js-object-to-json', icon: 'Code' },

  // Configuration
  { id: 'json-to-env', name: 'JSON to .env', description: 'Convert JSON objects to .env file format.', category: 'converter', slug: '/json-to-env', icon: 'ArrowRight' },
  { id: 'env-to-json', name: '.env to JSON', description: 'Parse .env files back into JSON format.', category: 'converter', slug: '/env-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-docker-compose', name: 'JSON to Docker Compose', description: 'Convert JSON data to Docker Compose YAML.', category: 'converter', slug: '/json-to-docker-compose', icon: 'ArrowRight' },
  { id: 'docker-compose-to-json', name: 'Docker Compose to JSON', description: 'Convert Docker Compose YAML to JSON format.', category: 'converter', slug: '/docker-compose-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-kubernetes', name: 'JSON to Kubernetes', description: 'Convert JSON data to Kubernetes manifest YAML.', category: 'converter', slug: '/json-to-kubernetes', icon: 'ArrowRight' },
  { id: 'kubernetes-to-json', name: 'Kubernetes to JSON', description: 'Convert Kubernetes manifest YAML to JSON format.', category: 'converter', slug: '/kubernetes-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-terraform', name: 'JSON to Terraform', description: 'Convert JSON data to Terraform variables format.', category: 'converter', slug: '/json-to-terraform', icon: 'ArrowRight' },
  { id: 'terraform-to-json', name: 'Terraform to JSON', description: 'Convert Terraform variables files to JSON format.', category: 'converter', slug: '/terraform-to-json', icon: 'ArrowLeft' },

  // Databases
  { id: 'json-to-sql-insert', name: 'JSON to SQL INSERT', description: 'Generate SQL INSERT statements from JSON data.', category: 'converter', slug: '/json-to-sql-insert', icon: 'Table' },
  { id: 'sql-to-json', name: 'SQL INSERT to JSON', description: 'Parse SQL INSERT statements into JSON format.', category: 'converter', slug: '/sql-to-json', icon: 'FileText' },
  { id: 'json-to-mongodb', name: 'JSON to MongoDB', description: 'Convert JSON data to MongoDB document format.', category: 'converter', slug: '/json-to-mongodb', icon: 'ArrowRight' },
  { id: 'mongodb-to-json', name: 'MongoDB to JSON', description: 'Convert MongoDB documents to standard JSON format.', category: 'converter', slug: '/mongodb-to-json', icon: 'ArrowLeft' },

  // API Formats
  { id: 'json-to-curl', name: 'JSON to cURL', description: 'Generate cURL commands from JSON request bodies.', category: 'converter', slug: '/json-to-curl', icon: 'ArrowRight' },
  { id: 'curl-to-json', name: 'cURL to JSON', description: 'Extract JSON request bodies from cURL commands.', category: 'converter', slug: '/curl-to-json', icon: 'ArrowLeft' },

  // Utilities (Markdown, Nested/Flat, Key-Value, Schema, NDJSON, GeoJSON, Escape)
  { id: 'json-to-markdown', name: 'JSON to Markdown', description: 'Convert JSON data to a Markdown code block with syntax highlighting.', category: 'converter', slug: '/json-to-markdown', icon: 'ArrowRight' },
  { id: 'markdown-to-json', name: 'Markdown to JSON', description: 'Extract JSON data from Markdown code blocks.', category: 'converter', slug: '/markdown-to-json', icon: 'ArrowLeft' },
  { id: 'nested-to-flat-json', name: 'Nested JSON to Flat', description: 'Flatten deeply nested JSON into dot-notation key-value pairs.', category: 'converter', slug: '/nested-to-flat-json', icon: 'ArrowRight' },
  { id: 'flat-to-nested-json', name: 'Flat JSON to Nested', description: 'Convert dot-notation flat JSON back to nested structure.', category: 'converter', slug: '/flat-to-nested-json', icon: 'ArrowLeft' },
  { id: 'json-to-key-value', name: 'JSON to Key-Value', description: 'Convert JSON objects to simple key:value pair lines.', category: 'converter', slug: '/json-to-key-value', icon: 'ArrowRight' },
  { id: 'key-value-to-json', name: 'Key-Value to JSON', description: 'Parse key:value pair lines into structured JSON.', category: 'converter', slug: '/key-value-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-schema', name: 'JSON to Schema', description: 'Generate a JSON Schema draft-07 from JSON data sample.', category: 'converter', slug: '/json-to-schema', icon: 'ArrowRight' },
  { id: 'schema-to-json', name: 'Schema to JSON', description: 'Generate sample JSON data from a JSON Schema definition.', category: 'converter', slug: '/schema-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-ndjson', name: 'JSON to NDJSON', description: 'Convert a JSON array to newline-delimited JSON format.', category: 'converter', slug: '/json-to-ndjson', icon: 'ArrowRight' },
  { id: 'ndjson-to-json', name: 'NDJSON to JSON', description: 'Parse newline-delimited JSON into a JSON array.', category: 'converter', slug: '/ndjson-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-geojson', name: 'JSON to GeoJSON', description: 'Convert JSON data with coordinates to GeoJSON FeatureCollection.', category: 'converter', slug: '/json-to-geojson', icon: 'Map' },
  { id: 'geojson-to-json', name: 'GeoJSON to JSON', description: 'Extract properties from GeoJSON features to standard JSON.', category: 'converter', slug: '/geojson-to-json', icon: 'ArrowLeft' },
  { id: 'json-escape', name: 'JSON Escape', description: 'Escape a JSON string for use in source code or queries.', category: 'converter', slug: '/json-escape', icon: 'ArrowRight' },
  { id: 'json-unescape', name: 'JSON Unescape', description: 'Unescape a previously escaped JSON string.', category: 'converter', slug: '/json-unescape', icon: 'ArrowLeft' },

  // JSON Utilities (Sort, Remove Nulls, Size, Merge, Depth, JSONPath)
  { id: 'json-sort-keys', name: 'JSON Sort Keys', description: 'Sort all JSON object keys alphabetically for consistent output.', category: 'formatter', slug: '/json-sort-keys', icon: 'ArrowUpDown' },
  { id: 'json-remove-nulls', name: 'JSON Remove Nulls', description: 'Remove all null values from JSON objects and arrays.', category: 'formatter', slug: '/json-remove-nulls', icon: 'XCircle' },
  { id: 'json-size-calculator', name: 'JSON Size Calculator', description: 'Calculate the byte size, element count, and depth of JSON data.', category: 'formatter', slug: '/json-size-calculator', icon: 'Calculator' },
  { id: 'json-merge', name: 'JSON Merge', description: 'Deep merge two or more JSON objects into one.', category: 'converter', slug: '/json-merge', icon: 'Merge' },
  { id: 'json-depth-analyzer', name: 'JSON Depth Analyzer', description: 'Analyze nesting depth, node count, and branching of JSON.', category: 'formatter', slug: '/json-depth-analyzer', icon: 'Layers' },
  { id: 'json-path-tester', name: 'JSONPath Tester', description: 'Test JSONPath expressions against JSON data and see results.', category: 'formatter', slug: '/json-path-tester', icon: 'Search' },

  // Databases
  { id: 'json-to-firestore', name: 'JSON to Firestore', description: 'Convert JSON data to Firestore document format with typed fields.', category: 'converter', slug: '/json-to-firestore', icon: 'ArrowRight' },
  { id: 'firestore-to-json', name: 'Firestore to JSON', description: 'Convert Firestore document format back to standard JSON.', category: 'converter', slug: '/firestore-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-graphql-schema', name: 'JSON to GraphQL Schema', description: 'Generate GraphQL type definitions from JSON data samples.', category: 'converter', slug: '/json-to-graphql-schema', icon: 'Code' },
  { id: 'graphql-schema-to-json', name: 'GraphQL Schema to JSON', description: 'Generate sample JSON data from GraphQL type definitions.', category: 'converter', slug: '/graphql-schema-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-openapi', name: 'JSON to OpenAPI', description: 'Generate OpenAPI 3.0 schema components from JSON samples.', category: 'converter', slug: '/json-to-openapi', icon: 'ArrowRight' },
  { id: 'openapi-to-json', name: 'OpenAPI to JSON', description: 'Extract sample JSON data from OpenAPI schema definitions.', category: 'converter', slug: '/openapi-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-binary', name: 'JSON to Binary', description: 'Convert JSON data into binary (0/1) string representation.', category: 'converter', slug: '/json-to-binary', icon: 'ArrowRight' },
  { id: 'binary-to-json', name: 'Binary to JSON', description: 'Convert binary strings back into readable JSON format.', category: 'converter', slug: '/binary-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-mermaid', name: 'JSON to Mermaid', description: 'Generate Mermaid.js flowchart diagrams from JSON structures.', category: 'converter', slug: '/json-to-mermaid', icon: 'GitBranch' },
  { id: 'mermaid-to-json', name: 'Mermaid to JSON', description: 'Parse Mermaid flowchart definitions into JSON format.', category: 'converter', slug: '/mermaid-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-readme', name: 'JSON to README', description: 'Convert JSON data to a structured README document.', category: 'converter', slug: '/json-to-readme', icon: 'FileText' },
  { id: 'readme-to-json', name: 'README to JSON', description: 'Extract JSON data from structured README documents.', category: 'converter', slug: '/readme-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-array', name: 'JSON Object to Array', description: 'Convert JSON objects to arrays of key-value pair objects.', category: 'converter', slug: '/json-to-array', icon: 'ArrowRight' },
  { id: 'array-to-json', name: 'Array to JSON Object', description: 'Convert arrays of key-value pairs back to JSON objects.', category: 'converter', slug: '/array-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-tree', name: 'JSON to Tree View', description: 'Generate a visual indented tree view from JSON data.', category: 'converter', slug: '/json-to-tree', icon: 'GitFork' },
  { id: 'tree-to-json', name: 'Tree View to JSON', description: 'Parse indented tree view back into structured JSON.', category: 'converter', slug: '/tree-to-json', icon: 'ArrowLeft' },
  { id: 'json-convert-arrays', name: 'JSON Convert to Object', description: 'Transpose array of objects into object of arrays.', category: 'converter', slug: '/json-convert-arrays', icon: 'ArrowRight' },
  { id: 'json-convert-objects', name: 'JSON Convert to Array', description: 'Transpose object of arrays back into array of objects.', category: 'converter', slug: '/json-convert-objects', icon: 'ArrowLeft' },

  // JSON Utilities
  { id: 'json-fake-generator', name: 'JSON Fake Data Generator', description: 'Generate realistic fake JSON data from a template schema.', category: 'generator', slug: '/json-fake-generator', icon: 'Wand' },
  { id: 'json-mock-generator', name: 'JSON Mock Generator', description: 'Generate mock API response data from a type template.', category: 'generator', slug: '/json-mock-generator', icon: 'Server' },
  { id: 'json-random-generator', name: 'JSON Random Generator', description: 'Generate random JSON data with configurable types and depth.', category: 'generator', slug: '/json-random-generator', icon: 'Shuffle' },
  { id: 'json-sample-generator', name: 'JSON Sample Generator', description: 'Generate deterministic sample JSON from a type template.', category: 'generator', slug: '/json-sample-generator', icon: 'FileOutput' },
  { id: 'json-statistics', name: 'JSON Statistics', description: 'Get detailed statistics about your JSON data structure.', category: 'formatter', slug: '/json-statistics', icon: 'BarChart3' },
  { id: 'json-key-counter', name: 'JSON Key Counter', description: 'Count key frequency and type breakdown across all objects.', category: 'formatter', slug: '/json-key-counter', icon: 'Hash' },
  { id: 'json-string-analyzer', name: 'JSON String Analyzer', description: 'Analyze all string values in JSON for length statistics.', category: 'formatter', slug: '/json-string-analyzer', icon: 'TextSelect' },
  { id: 'json-filter', name: 'JSON Filter', description: 'Filter JSON to only include specified dot-notation paths.', category: 'formatter', slug: '/json-filter', icon: 'Filter' },
  { id: 'json-extract', name: 'JSON Extract', description: 'Extract values from JSON using dot-notation path expressions.', category: 'formatter', slug: '/json-extract', icon: 'SearchCheck' },
  { id: 'json-remove-empty', name: 'JSON Remove Empty', description: 'Remove all empty objects and arrays from JSON.', category: 'formatter', slug: '/json-remove-empty', icon: 'Trash2' },
  { id: 'json-remove-duplicates', name: 'JSON Remove Duplicates', description: 'Remove duplicate objects from JSON arrays.', category: 'formatter', slug: '/json-remove-duplicates', icon: 'CopyX' },
  { id: 'json-detect-circular', name: 'JSON Detect Circular', description: 'Detect circular references in JSON data structures.', category: 'formatter', slug: '/json-detect-circular', icon: 'AlertTriangle' },
  { id: 'json-detect-duplicate-keys', name: 'JSON Detect Duplicate Keys', description: 'Detect duplicate keys within the same object level.', category: 'formatter', slug: '/json-detect-duplicate-keys', icon: 'Columns' },
  { id: 'json-rename-keys', name: 'JSON Rename Keys', description: 'Rename JSON object keys using a key mapping definition.', category: 'formatter', slug: '/json-rename-keys', icon: 'Pencil' },
  { id: 'json-normalize', name: 'JSON Normalize', description: 'Normalize JSON by sorting keys consistently at all levels.', category: 'formatter', slug: '/json-normalize', icon: 'CheckSquare' },
  { id: 'json-custom-stringify', name: 'JSON Custom Stringify', description: 'Stringify JSON with configurable indentation and sorting.', category: 'formatter', slug: '/json-custom-stringify', icon: 'Settings2' },
  { id: 'json-to-inline', name: 'JSON to Inline', description: 'Convert JSON to a single-line or custom-indented inline format.', category: 'formatter', slug: '/json-to-inline', icon: 'Minimize2' },
  { id: 'json-sort-arrays', name: 'JSON Sort Arrays', description: 'Sort array elements (strings and numbers) within JSON.', category: 'formatter', slug: '/json-sort-arrays', icon: 'ArrowUpDown' },
  { id: 'json-merge-patch', name: 'JSON Merge Patch', description: 'Apply RFC 7396 JSON Merge Patch to a target JSON object.', category: 'converter', slug: '/json-merge-patch', icon: 'Merge' },
  { id: 'json-split', name: 'JSON Split', description: 'Split a JSON array into smaller chunks of configurable size.', category: 'formatter', slug: '/json-split', icon: 'Split' },
  { id: 'json-pointer-tester', name: 'JSON Pointer Tester', description: 'Test RFC 6901 JSON Pointer expressions against JSON data.', category: 'formatter', slug: '/json-pointer-tester', icon: 'Crosshair' },

  // Database SQL Generators
  { id: 'json-to-postgresql', name: 'JSON to PostgreSQL', description: 'Generate PostgreSQL CREATE TABLE and INSERT statements from JSON.', category: 'converter', slug: '/json-to-postgresql', icon: 'Database' },
  { id: 'postgresql-to-json', name: 'PostgreSQL to JSON', description: 'Parse PostgreSQL INSERT statements back into JSON format.', category: 'converter', slug: '/postgresql-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-mysql', name: 'JSON to MySQL', description: 'Generate MySQL CREATE TABLE and INSERT statements from JSON.', category: 'converter', slug: '/json-to-mysql', icon: 'Database' },
  { id: 'mysql-to-json', name: 'MySQL to JSON', description: 'Parse MySQL INSERT statements back into JSON format.', category: 'converter', slug: '/mysql-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-sqlite', name: 'JSON to SQLite', description: 'Generate SQLite CREATE TABLE and INSERT statements from JSON.', category: 'converter', slug: '/json-to-sqlite', icon: 'Database' },
  { id: 'sqlite-to-json', name: 'SQLite to JSON', description: 'Parse SQLite INSERT statements back into JSON format.', category: 'converter', slug: '/sqlite-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-sql-server', name: 'JSON to SQL Server', description: 'Generate SQL Server CREATE TABLE and INSERT statements from JSON.', category: 'converter', slug: '/json-to-sql-server', icon: 'Database' },
  { id: 'sql-server-to-json', name: 'SQL Server to JSON', description: 'Parse SQL Server INSERT statements back into JSON format.', category: 'converter', slug: '/sql-server-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-oracle', name: 'JSON to Oracle', description: 'Generate Oracle SQL CREATE TABLE and INSERT statements from JSON.', category: 'converter', slug: '/json-to-oracle', icon: 'Database' },
  { id: 'oracle-to-json', name: 'Oracle to JSON', description: 'Parse Oracle SQL INSERT statements back into JSON format.', category: 'converter', slug: '/oracle-to-json', icon: 'ArrowLeft' },

  // API & Data Formats
  { id: 'json-to-postman', name: 'JSON to Postman', description: 'Generate Postman Collection v2.1 from JSON request definitions.', category: 'converter', slug: '/json-to-postman', icon: 'ArrowRight' },
  { id: 'postman-to-json', name: 'Postman to JSON', description: 'Extract request definitions from Postman Collection JSON.', category: 'converter', slug: '/postman-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-bson', name: 'JSON to BSON', description: 'Convert JSON to MongoDB extended JSON (BSON) format.', category: 'converter', slug: '/json-to-bson', icon: 'ArrowRight' },
  { id: 'bson-to-json', name: 'BSON to JSON', description: 'Convert MongoDB extended JSON (BSON) back to standard JSON.', category: 'converter', slug: '/bson-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-graphviz', name: 'JSON to Graphviz', description: 'Generate Graphviz DOT graph from JSON data structure.', category: 'converter', slug: '/json-to-graphviz', icon: 'GitBranch' },
  { id: 'graphviz-to-json', name: 'Graphviz to JSON', description: 'Parse Graphviz DOT format back into JSON structure.', category: 'converter', slug: '/graphviz-to-json', icon: 'ArrowLeft' },
  { id: 'jsonc-to-json', name: 'JSONC to JSON', description: 'Strip comments from JSONC (JSON with Comments) to produce valid JSON.', category: 'converter', slug: '/jsonc-to-json', icon: 'ArrowRight' },
  { id: 'json-to-jsonc', name: 'JSON to JSONC', description: 'Add inline comments to JSON keys to create JSONC format.', category: 'converter', slug: '/json-to-jsonc', icon: 'ArrowLeft' },

  // Security
  { id: 'json-encrypt', name: 'JSON Encrypt', description: 'Encrypt JSON data with XOR cipher + Base64 encoding.', category: 'converter', slug: '/json-encrypt', icon: 'Lock' },
  { id: 'json-decrypt', name: 'JSON Decrypt', description: 'Decrypt previously encrypted JSON data back to readable format.', category: 'converter', slug: '/json-decrypt', icon: 'Unlock' },
  { id: 'json-mask-data', name: 'JSON Mask Data', description: 'Mask sensitive fields in JSON (passwords, tokens, emails, SSN).', category: 'formatter', slug: '/json-mask-data', icon: 'EyeOff' },

  // Analysis & Linting
  { id: 'json-linter', name: 'JSON Linter', description: 'Lint JSON for style issues, duplicate keys, and naming conventions.', category: 'formatter', slug: '/json-linter', icon: 'CheckCheck' },
  { id: 'json-repair', name: 'JSON Repair', description: 'Attempt to repair invalid JSON by fixing quotes, trailing commas, and comments.', category: 'formatter', slug: '/json-repair', icon: 'Wrench' },
  { id: 'json-search', name: 'JSON Search', description: 'Search within JSON data for matching values and keys.', category: 'formatter', slug: '/json-search', icon: 'Search' },
  { id: 'json-type-detector', name: 'JSON Type Detector', description: 'Detect and report field types across all objects in JSON.', category: 'formatter', slug: '/json-type-detector', icon: 'Binary' },
  { id: 'json-compare', name: 'JSON Compare', description: 'Compare two JSON objects to find added, removed, and changed fields.', category: 'compare', slug: '/json-compare', icon: 'Columns' },
  { id: 'json-schema-validator', name: 'JSON Schema Validator', description: 'Validate JSON data against a JSON Schema (draft-07).', category: 'validator', slug: '/json-schema-validator', icon: 'Shield' },

  // Transformers
  { id: 'json-case-converter', name: 'JSON Case Converter', description: 'Convert JSON key casing between camelCase, snake_case, kebab-case, PascalCase.', category: 'formatter', slug: '/json-case-converter', icon: 'CaseSensitive' },
  { id: 'json-date-formatter', name: 'JSON Date Formatter', description: 'Convert date strings in JSON between ISO, locale, Unix, and UTC formats.', category: 'formatter', slug: '/json-date-formatter', icon: 'Calendar' },
  { id: 'json-schema-to-typescript', name: 'JSON Schema to TypeScript', description: 'Generate TypeScript interfaces from JSON data samples.', category: 'converter', slug: '/json-schema-to-typescript', icon: 'Code' },

  // Resources (Copy, Download, Upload, Viewers, Extractors, Compression, Patch)
  { id: 'json-copy', name: 'JSON Copy', description: 'Format and copy JSON data to your clipboard with one click.', category: 'formatter', slug: '/json-copy', icon: 'Copy' },
  { id: 'json-download', name: 'JSON Download', description: 'Format and download JSON data as a .json file.', category: 'formatter', slug: '/json-download', icon: 'Download' },
  { id: 'json-upload', name: 'JSON Upload', description: 'Upload a .json file and view or process its contents instantly.', category: 'formatter', slug: '/json-upload', icon: 'Upload' },
  { id: 'json-file-viewer', name: 'JSON File Viewer', description: 'Open and view any .json file in a readable tree format.', category: 'viewer', slug: '/json-file-viewer', icon: 'FileText' },
  { id: 'json-clipboard-viewer', name: 'JSON Clipboard Viewer', description: 'View and explore JSON data pasted from your clipboard.', category: 'viewer', slug: '/json-clipboard-viewer', icon: 'Clipboard' },
  { id: 'json-explorer', name: 'JSON Explorer', description: 'Interactively explore JSON data with expandable tree view.', category: 'viewer', slug: '/json-explorer', icon: 'Search' },
  { id: 'json-expand', name: 'JSON Expand', description: 'Expand minified JSON to a beautifully formatted tree view.', category: 'formatter', slug: '/json-expand', icon: 'Maximize2' },
  { id: 'json-collapse', name: 'JSON Collapse', description: 'Collapse formatted JSON to a compact single-line format.', category: 'formatter', slug: '/json-collapse', icon: 'Minimize2' },
  { id: 'json-extract-objects', name: 'JSON Extract Objects', description: 'Extract all object nodes from JSON data into a flat list.', category: 'formatter', slug: '/json-extract-objects', icon: 'SearchCheck' },
  { id: 'json-extract-arrays', name: 'JSON Extract Arrays', description: 'Extract all array nodes from JSON data into a flat list.', category: 'formatter', slug: '/json-extract-arrays', icon: 'List' },
  { id: 'json-denormalize', name: 'JSON Denormalize', description: 'Randomize key order in JSON objects to denormalize the structure.', category: 'formatter', slug: '/json-denormalize', icon: 'Shuffle' },
  { id: 'json-pointer-generator', name: 'JSON Pointer Generator', description: 'Generate RFC 6901 JSON Pointers for every node in your JSON.', category: 'formatter', slug: '/json-pointer-generator', icon: 'Crosshair' },
  { id: 'json-compress', name: 'JSON Compress (Deflate)', description: 'Compress JSON data using Deflate algorithm and output Base64.', category: 'formatter', slug: '/json-compress', icon: 'Compress' },
  { id: 'json-decompress', name: 'JSON Decompress (Inflate)', description: 'Decompress previously Deflate-compressed JSON from Base64.', category: 'formatter', slug: '/json-decompress', icon: 'Expand' },
  { id: 'json-gzip', name: 'JSON Gzip', description: 'Gzip-compress JSON data and output Base64-encoded result.', category: 'formatter', slug: '/json-gzip', icon: 'FileArchive' },
  { id: 'json-gunzip', name: 'JSON Gunzip', description: 'Decompress Gzip-compressed JSON from Base64 back to readable text.', category: 'formatter', slug: '/json-gunzip', icon: 'FileOutput' },
  { id: 'json-version-diff', name: 'JSON Version Diff', description: 'Compare two versions of JSON data side by side with change tracking.', category: 'compare', slug: '/json-version-diff', icon: 'GitCompare' },
  { id: 'json-patch-generator', name: 'JSON Patch Generator', description: 'Generate RFC 6902 JSON Patch operations between two JSON objects.', category: 'converter', slug: '/json-patch-generator', icon: 'FileDiff' },
  { id: 'json-patch-validator', name: 'JSON Patch Validator', description: 'Validate RFC 6902 JSON Patch operation lists for correctness.', category: 'validator', slug: '/json-patch-validator', icon: 'Shield' },

  // Batch 5: Remaining Tools
  { id: 'json-to-xlsx', name: 'JSON to Excel (XLSX)', description: 'Convert JSON data to a downloadable Excel XLSX spreadsheet.', category: 'converter', slug: '/json-to-xlsx', icon: 'Table' },
  { id: 'xlsx-to-json', name: 'Excel (XLSX) to JSON', description: 'Convert Excel XLSX files back into structured JSON format.', category: 'converter', slug: '/xlsx-to-json', icon: 'FileText' },
  { id: 'json-url-viewer', name: 'JSON URL Viewer', description: 'Fetch and display JSON data from a remote URL endpoint.', category: 'viewer', slug: '/json-url-viewer', icon: 'Globe' },
  { id: 'json-merge-files', name: 'JSON Merge Files', description: 'Merge multiple JSON objects pasted as separate blocks into one.', category: 'converter', slug: '/json-merge-files', icon: 'Merge' },
  { id: 'json-to-qrcode', name: 'JSON to QR Code', description: 'Generate a QR code image from any JSON data.', category: 'converter', slug: '/json-to-qrcode', icon: 'QrCode' },
  { id: 'json-to-image', name: 'JSON to SVG Image', description: 'Render JSON data as a syntax-highlighted SVG image.', category: 'converter', slug: '/json-to-image', icon: 'Image' },
  { id: 'json-to-pdf', name: 'JSON to PDF', description: 'Generate a downloadable PDF document from JSON data.', category: 'converter', slug: '/json-to-pdf', icon: 'FileText' },
  { id: 'json-value-analyzer', name: 'JSON Value Analyzer', description: 'Analyze value frequency and distribution across JSON fields.', category: 'formatter', slug: '/json-value-analyzer', icon: 'BarChart3' },
  { id: 'json-collection-counter', name: 'JSON Collection Counter', description: 'Count field presence, types, and nulls across array items.', category: 'formatter', slug: '/json-collection-counter', icon: 'Hash' },
  { id: 'json-array-diff', name: 'JSON Array Diff', description: 'Compare two JSON arrays to find added, removed, and unchanged items.', category: 'compare', slug: '/json-array-diff', icon: 'Columns' },

  // ---- Batch 6: Remaining 30 Tools ----

  { id: 'json-to-swagger', name: 'JSON to Swagger', description: 'Generate Swagger 2.0 API definitions from JSON data samples.', category: 'converter', slug: '/json-to-swagger', icon: 'ArrowRight' },
  { id: 'swagger-to-json', name: 'Swagger to JSON', description: 'Extract sample JSON data from Swagger 2.0 API definitions.', category: 'converter', slug: '/swagger-to-json', icon: 'ArrowLeft' },
  { id: 'json-to-word', name: 'JSON to Word', description: 'Convert JSON data to a downloadable Word document format.', category: 'converter', slug: '/json-to-word', icon: 'FileText' },
  { id: 'word-to-json', name: 'Word to JSON', description: 'Extract JSON data from Word document content.', category: 'converter', slug: '/word-to-json', icon: 'ArrowLeft' },
  { id: 'pdf-to-json', name: 'PDF to JSON', description: 'Extract text content from PDF data and structure it as JSON.', category: 'converter', slug: '/pdf-to-json', icon: 'FileText' },
  { id: 'qr-code-to-json', name: 'QR Code to JSON', description: 'Decode QR code text data back into structured JSON format.', category: 'converter', slug: '/qr-code-to-json', icon: 'QrCode' },
  { id: 'json-to-barcode', name: 'JSON to Barcode', description: 'Generate a Code 39 barcode SVG image from your JSON data.', category: 'converter', slug: '/json-to-barcode', icon: 'ArrowRight' },
  { id: 'barcode-to-json', name: 'Barcode to JSON', description: 'Extract JSON data from barcode text content.', category: 'converter', slug: '/barcode-to-json', icon: 'ArrowLeft' },
  { id: 'image-to-json', name: 'Image to JSON (OCR)', description: 'Extract JSON-like data structures from recognized text content.', category: 'converter', slug: '/image-to-json', icon: 'Image' },
  { id: 'json-to-python-dict', name: 'JSON to Python Dict', description: 'Generate Python dictionary literal syntax from JSON samples.', category: 'converter', slug: '/json-to-python-dict', icon: 'Code' },
  { id: 'fake-data-to-json', name: 'Fake Data to JSON', description: 'Infer a template schema from JSON data for regeneration.', category: 'generator', slug: '/fake-data-to-json', icon: 'Wand' },
  { id: 'json-slice', name: 'JSON Slice', description: 'Extract a sub-array slice from JSON arrays by start and end indices.', category: 'formatter', slug: '/json-slice', icon: 'Scissors' },
  { id: 'extract-keys', name: 'Extract Keys', description: 'Extract all unique object keys from JSON data.', category: 'formatter', slug: '/extract-keys', icon: 'SearchCheck' },
  { id: 'extract-values', name: 'Extract Values', description: 'Extract all values from JSON data with unique count.', category: 'formatter', slug: '/extract-values', icon: 'List' },
  { id: 'extract-nested-objects', name: 'Extract Nested Objects', description: 'Extract all nested objects from JSON into a flat list.', category: 'formatter', slug: '/extract-nested-objects', icon: 'Layers' },
  { id: 'json-array-counter', name: 'JSON Array Counter', description: 'Count all arrays in JSON and report their sizes and nesting.', category: 'formatter', slug: '/json-array-counter', icon: 'Hash' },
  { id: 'json-schema-generator', name: 'JSON Schema Generator', description: 'Generate a JSON Schema (draft-07) from JSON data samples.', category: 'generator', slug: '/json-schema-generator', icon: 'Braces' },
  { id: 'validate-uploaded-json', name: 'Validate Uploaded JSON', description: 'Validate JSON data from file uploads with detailed feedback.', category: 'validator', slug: '/validate-uploaded-json', icon: 'Upload' },
  { id: 'convert-json-file', name: 'Convert JSON File', description: 'Process and analyze JSON file contents with size and type info.', category: 'converter', slug: '/convert-json-file', icon: 'FileUp' },
  { id: 'json-live-preview', name: 'JSON Live Preview', description: 'Preview JSON data with real-time structure analysis and formatting.', category: 'viewer', slug: '/json-live-preview', icon: 'Eye' },

  // ---- Batch 7: Fill to 250+ ----
  { id: 'json-to-haskell', name: 'JSON to Haskell', description: 'Generate Haskell data type definitions from JSON data samples.', category: 'converter', slug: '/json-to-haskell', icon: 'Code' },
  { id: 'json-to-elm', name: 'JSON to Elm', description: 'Generate Elm type aliases from JSON data samples.', category: 'converter', slug: '/json-to-elm', icon: 'Code' },
  { id: 'json-to-ocaml', name: 'JSON to OCaml', description: 'Generate OCaml type definitions with Yojson deriving from JSON samples.', category: 'converter', slug: '/json-to-ocaml', icon: 'Code' },
  { id: 'json-to-zig', name: 'JSON to Zig', description: 'Generate Zig struct definitions with JSON support from JSON data samples.', category: 'converter', slug: '/json-to-zig', icon: 'Code' },
  { id: 'array-to-object-json', name: 'Array JSON to Object JSON', description: 'Transpose an array of objects into an object of arrays.', category: 'converter', slug: '/array-to-object-json', icon: 'ArrowRight' },
  { id: 'object-to-array-json', name: 'Object JSON to Array JSON', description: 'Transpose an object of arrays back into an array of objects.', category: 'converter', slug: '/object-to-array-json', icon: 'ArrowLeft' },
  { id: 'json-deflate', name: 'JSON Deflate', description: 'Compress JSON using the Deflate algorithm to Base64.', category: 'formatter', slug: '/json-deflate', icon: 'Compress' },
  { id: 'json-inflate', name: 'JSON Inflate', description: 'Decompress previously Deflate-compressed JSON from Base64.', category: 'formatter', slug: '/json-inflate', icon: 'Expand' },
  { id: 'fetch-json-from-url', name: 'Fetch JSON from URL', description: 'Fetch and display JSON data from any REST API URL endpoint.', category: 'viewer', slug: '/fetch-json-from-url', icon: 'Globe' },
  { id: 'api-json-viewer', name: 'API JSON Viewer', description: 'View and explore JSON responses from REST API endpoints.', category: 'viewer', slug: '/api-json-viewer', icon: 'Server' },

  // ---- Synonym / Alias Tools ----
  { id: 'json-beautifier', name: 'JSON Beautifier', description: 'Beautify and format JSON with proper indentation for readability.', category: 'formatter', slug: '/json-beautifier', icon: 'Braces' },
  { id: 'json-pretty-print', name: 'JSON Pretty Print', description: 'Pretty-print JSON data with customizable indentation.', category: 'formatter', slug: '/json-pretty-print', icon: 'Braces' },
  { id: 'json-compact', name: 'JSON Compact', description: 'Compact JSON by removing all whitespace for minimal file size.', category: 'formatter', slug: '/json-compact', icon: 'Compress' },
  { id: 'json-indenter', name: 'JSON Indenter', description: 'Apply custom indentation (spaces or tabs) to your JSON data.', category: 'formatter', slug: '/json-indenter', icon: 'Indent' },
  { id: 'json-syntax-checker', name: 'JSON Syntax Checker', description: 'Check JSON syntax and get detailed error messages for invalid input.', category: 'validator', slug: '/json-syntax-checker', icon: 'CheckCircle' },
  { id: 'json-fixer', name: 'JSON Fixer', description: 'Fix common JSON errors like trailing commas, missing quotes, and single quotes.', category: 'validator', slug: '/json-fixer', icon: 'Wrench' },
  { id: 'invalid-json-repair', name: 'Invalid JSON Repair', description: 'Repair malformed JSON by detecting and fixing common syntax issues.', category: 'validator', slug: '/invalid-json-repair', icon: 'Wrench' },
  { id: 'json-tree-viewer', name: 'JSON Tree Viewer', description: 'Visualize JSON data as an interactive tree structure.', category: 'viewer', slug: '/json-tree-viewer', icon: 'GitBranch' },
  { id: 'json-python-dataclass', name: 'JSON to Python Dataclass', description: 'Generate Python dataclass definitions from JSON data samples.', category: 'converter', slug: '/json-python-dataclass', icon: 'Code' },
]
