'use client'
import ToolLayout from '@/components/tools/ToolLayout'
import { arbToJson } from '@/lib/converters'

const example = '{"appName":"My App","@appName":{"description":"The app name"},"welcome":"Welcome","@welcome":{"description":"Welcome message"}}'

export default function ToolPageClient() {
  return (
    <>
      <ToolLayout
        title="ARB to JSON - Flutter ARB Converter"
        description="Convert Flutter ARB (Application Resource Bundle) files to clean JSON."
        inputPlaceholder="Paste your ARB JSON here..."
        outputPlaceholder="Converted JSON will appear here..."
        convertLabel="Convert to JSON"
        onConvert={arbToJson}
        exampleInput={example}
        inputLanguage="json"
        outputLanguage="json"
        toolSlug="arb-to-json"
      />
      <article className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-16 prose prose-slate dark:prose-invert">
        <h2>What Is ARB to JSON?</h2>
        <p>ARB (Application Resource Bundle) is the localization file format used by Flutter and Dart projects. It contains translation strings alongside metadata entries prefixed with <code>@</code>, and converting ARB to JSON strips this metadata to produce clean key-value translation objects.</p>
        <p>This is used for:</p>
        <ul>
          <li><strong>Flutter Localization</strong>: Extracting clean translation pairs from ARB files generated by Flutter's l10n tooling for use in non-Flutter JavaScript or backend projects.</li>
          <li><strong>Metadata Removal</strong>: Stripping ARB metadata descriptors like <code>@key.description</code> and <code>@key.type</code> to produce minimal JSON compatible with any i18n library.</li>
          <li><strong>Cross-Platform Sharing</strong>: Converting Flutter-specific ARB files into universal JSON that can be consumed by iOS, web, or server-side applications.</li>
        </ul>
        <h2>How to Use ARB to JSON Online</h2>
        <ol>
          <li><strong>Paste your ARB content</strong>: Copy the contents of your Flutter ARB file, which includes translation keys, values, and @-prefixed metadata entries.</li>
          <li><strong>Click Convert</strong>: Press the Convert to JSON button to automatically strip all metadata and produce a flat JSON object of key-value translation pairs.</li>
          <li><strong>Copy or download</strong>: Copy the clean JSON to your clipboard or download it for integration with any JSON-compatible system.</li>
        </ol>
        <h2>Frequently Asked Questions</h2>
        <h3>What are the @-prefixed keys in ARB files?</h3>
        <p>ARB files use keys starting with <code>@</code> to store metadata about translation entries, such as descriptions, placeholders, and resource attributes. This tool automatically filters out these metadata keys, returning only the actual translation content.</p>
        <h3>Is this tool safe?</h3>
        <p>Yes. All processing happens 100% client-side in your browser. Nothing is uploaded to any server.</p>
        <h3>Is this tool free?</h3>
        <p>Yes, completely free with no usage limits or registration required.</p>
        <h2>Real-World Examples</h2>
        <p>Flutter teams building cross-platform mobile apps often use ARB files as their source of truth for translations. When those same translations need to be shared with a companion web app built in React or with a Node.js backend, this ARB to JSON converter provides the bridge between Flutter's ecosystem and the broader JavaScript ecosystem.</p>
        <h2>Related Tools</h2>
        <ul>
          <li><a href="/json-to-ios-strings">JSON to iOS .strings</a> — Convert JSON to Apple iOS localization format</li>
          <li><a href="/strings-xml-to-json">strings.xml to JSON</a> — Convert Android strings.xml resource files to JSON</li>
          <li><a href="/xliff-to-json">XLIFF to JSON</a> — Convert XLIFF translation files to JSON</li>
        </ul>
      </article>
    </>
  )
}
