'use client'
import ToolLayout from '@/components/tools/ToolLayout'
import { harViewer } from '@/lib/converters'

const example = '{"log":{"version":"1.2","creator":{"name":"JSONKits","version":"1.0"},"entries":[{"request":{"method":"GET","url":"https://jsonkits.com/api"},"response":{"status":200,"statusText":"OK","content":{"mimeType":"application/json"},"bodySize":100},"timings":{"wait":50,"receive":100},"startedDateTime":"2024-01-01T00:00:00Z"}]}}'

export default function ToolPageClient() {
  return (
    <>
      <ToolLayout
        title="HAR Viewer"
        description="View and analyze HTTP Archive (HAR) files with request and response details."
        inputPlaceholder="Paste your HAR JSON here..."
        outputPlaceholder="Analyzed HAR data will appear here..."
        convertLabel="View HAR"
        onConvert={harViewer}
        exampleInput={example}
        inputLanguage="json"
        outputLanguage="json"
        toolSlug="har-viewer"
      />
      <article className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-16 prose prose-slate dark:prose-invert">
        <h2>What Is HAR Viewer?</h2>
        <p>An HAR Viewer is a tool that parses and displays HTTP Archive (HAR) files in a readable, structured format. HAR files are JSON-formatted archives generated by browsers like Chrome, Firefox, and Safari that capture detailed network request and response data during page loads.</p>
        <p>With the JSONKits HAR Viewer, you can inspect every request method, URL, HTTP status code, timing waterfall, and response payload from your browser network logs. This is essential for:</p>
        <ul>
          <li><strong>Performance debugging</strong>: Analyze page load timings to identify slow requests and bottlenecks.</li>
          <li><strong>API inspection</strong>: Review request headers, response bodies, and status codes across all network calls.</li>
          <li><strong>QA and testing</strong>: Export HAR files from test sessions and share network logs with developers for root-cause analysis.</li>
        </ul>
        <h2>How to View HAR Files Online</h2>
        <ol>
          <li><strong>Export your HAR file</strong>: Open your browser's DevTools (F12), go to the Network tab, perform the page load, right-click any request, and select "Save all as HAR with content."</li>
          <li><strong>Paste the HAR data</strong>: Copy the contents of your HAR file and paste them into the input editor on this page.</li>
          <li><strong>Click View HAR</strong>: Press the "View HAR" button to parse and analyze the archive instantly.</li>
          <li><strong>Review the results</strong>: Browse through every request entry, inspect timing details, request/response headers, and response bodies in the structured output.</li>
        </ol>
        <h2>Frequently Asked Questions</h2>
        <h3>Can I view HAR files from any browser?</h3>
        <p>Yes. The HAR format is standardized across all major browsers including Chrome, Firefox, Safari, and Edge. Simply export the HAR file from your browser's developer tools and paste it into this viewer.</p>
        <h3>Is this tool safe?</h3>
        <p>Yes. All processing happens 100% client-side in your browser.</p>
        <h3>Is this tool free?</h3>
        <p>Yes, completely free with no usage limits.</p>
        <h2>Real-World Examples</h2>
        <p>Web developers routinely use HAR viewers when investigating slow page loads, debugging API integration issues, or auditing third-party script performance. For example, a front-end engineer might export a HAR file from a production e-commerce site to discover that an unoptimized image CDN is causing a 3-second waterfall delay on mobile connections.</p>
        <h2>Related Tools</h2>
        <ul>
          <li><a href="/har-to-json">HAR to JSON</a> — Extract structured JSON data from HAR file entries</li>
          <li><a href="/json-beautifier">JSON Beautifier</a> — Format and beautify JSON data for readability</li>
          <li><a href="/json-compare">JSON Compare</a> — Compare two JSON objects side by side</li>
        </ul>
      </article>
    </>
  )
}
